#Tomcat config
server:
  port: 8081

project:
  name:

#半小时限制未支付订单为20个
order:
  create_frequency_value: 20
  # 单位：秒
  create_frequency_expire: 1800

#更新用户信息频率：7天1次
user:
  sync_info_day: 7


logging:
  level:
    root: error
  file:
    path: C:\code\wechat.pay

spring:

  # data source config
  datasource:
    url: jdbc:mysql://120.24.168.210:3306/wechat_pay?serverTimezone=GMT%2B8&characterEncoding=utf-8&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: X5Gtd439xh
    driver-class-name: com.mysql.cj.jdbc.Driver

  # jpa config
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        enable_lazy_load_no_trans: true
#        generate_statistics: true
        order_inserts: true
        jdbc:
          batch_size: 1000

  # thymeleaf config
  thymeleaf:
    cache: false

  #redis config
  redis:
    database: 0
    host: 120.24.168.210
    port: 6379
    password: TX7hs39zM
    lettuce:
      pool:
        max-active: 100
        max-wait: 10
        max-idle: 100
        min-idle: 0

# wechat config
WX:
  appId: wxb0fd8d11f36f012c
  mchId: 1564034741
  key:  ndilsr9CDZLutgPwy5E16OWpSJf2xvez
  appSecret: 9c9cb54e3b9d2684ecdf8b39b17c3cc6
  SSlCertPath:
  SSlCertPassword:
  notifyUrl:
    pay: http://www.hongdujuan.xiaoheikeji.net/wxpay/pay/payNotify
    refund: http://www.hongdujuan.xiaoheikeji.net/wxpay/pay/refundNotify
  serverUrl: http://www.hongdujuan.xiaoheikeji.net/wxpay
  tokenServerUrl:

